---
kind: pipeline
type: docker
name: release

steps:
  - name: build & push release
    image: thegeeklab/drone-docker-buildx:20.11@sha256:327b6fb15dc841cf80c7c429f60d695efd7c7a476fe363afac25a58befd4c203
    settings:
      auto_tag: true
      repo: mazzolino/docker-compose
      build_args:
        - DOCKER_VERSION=20.10.12
        - COMPOSE_VERSION=2.2.3
      platforms:
        - linux/amd64
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

trigger:
  event:
    exclude:
      - pull_request
